# Generated by Django 4.1.1 on 2022-10-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='username',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
