# Generated by Django 4.1.3 on 2022-11-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_17_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='nombre_usuario',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='Modelo',
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.CharField(default=30, max_length=100),
            preserve_default=False,
        ),
    ]
