# Generated by Django 4.1.3 on 2022-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_17_app', '0002_rename_nombre_usuario_auto_marca_remove_auto_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='patente',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
