# Generated by Django 4.1.3 on 2022-11-21 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('introapp', '0002_comentario_post_delete_algo_comentario_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(default=30, upload_to='comentarios_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
