# Generated by Django 4.1.3 on 2022-11-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0004_alter_comentario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='comentarios_img'),
        ),
    ]
