# Generated by Django 4.1.3 on 2022-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0005_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='post_img'),
        ),
    ]
