# Generated by Django 4.1.3 on 2022-11-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0006_alter_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='imagen2',
        ),
    ]
