# Generated by Django 4.1.3 on 2022-11-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0008_rename_imagen2_post_imagen_remove_comentario_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='imagen2',
        ),
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='comentarios_img'),
        ),
    ]
