# Generated by Django 4.1.3 on 2022-11-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0009_rename_imagen_post_imagen2_comentario_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen2',
            new_name='imagen_ad',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, default=21, upload_to='comentarios_img'),
            preserve_default=False,
        ),
    ]
