# Generated by Django 4.1.3 on 2022-11-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introapp', '0010_rename_imagen2_post_imagen_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen_ad',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='postimg'),
        ),
    ]
